---
name: Deploy Pollination App
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to Pollination Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set-environment
        id: set-environment
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pollination-apps
      - name: deploy app to pollination
        run: |
          pollination-apps deploy . --owner nicolas --name "Viewer Sample" --tag ${{ env.RELEASE_VERSION }} --public
        env:
          POLLINATION_TOKEN: ${{ secrets.POLLINATION_TOKEN }}

